import { RawJob } from './normalizer'

export function getCameroonSeeds(): RawJob[] {
  return [
    {
      external_id: 'seed_flutterwave_react_2024',
      title: 'Senior React Developer',
      company_name: 'Flutterwave',
      location: 'Lagos, Nigeria (Remote)',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'senior',
      description: 'Join Africa\'s leading payments company. Build React applications used by millions across the continent. We hire from anywhere in Africa.',
      requirements: '4+ years React, TypeScript, REST APIs. Experience with fintech a plus. Strong communication skills.',
      tags: ['React', 'TypeScript', 'Fintech', 'Node.js', 'REST APIs'],
      salary_min: 60000, salary_max: 90000, salary_currency: 'USD',
      external_url: 'https://flutterwave.com/us/careers',
      source: 'tier1', source_name: 'Flutterwave', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_andela_fullstack_2024',
      title: 'Full Stack Developer',
      company_name: 'Andela',
      location: 'Pan-Africa Remote',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'mid',
      description: 'Andela connects African engineers with global companies. Apply to join our vetted talent network and work with world-class US/EU companies.',
      requirements: '3+ years full stack development. React or Vue, Node.js or Python. Strong English communication.',
      tags: ['React', 'Node.js', 'Python', 'Full Stack', 'Remote Work'],
      salary_min: 50000, salary_max: 80000, salary_currency: 'USD',
      external_url: 'https://andela.com/apply',
      source: 'tier1', source_name: 'Andela', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_wave_backend_2024',
      title: 'Backend Engineer (Python)',
      company_name: 'Wave Mobile Money',
      location: 'Dakar, Senegal (Remote OK)',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'mid',
      description: 'Wave is building mobile money for Africa. We actively recruit from Francophone West Africa. French language skills are a plus.',
      requirements: 'Python 3+, PostgreSQL, strong problem-solving. Experience with distributed systems preferred.',
      tags: ['Python', 'PostgreSQL', 'Django', 'Fintech', 'French'],
      salary_min: 70000, salary_max: 100000, salary_currency: 'USD',
      external_url: 'https://wave.com/en/careers',
      source: 'tier1', source_name: 'Wave', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_paystack_data_2024',
      title: 'Data Analyst',
      company_name: 'Paystack (Stripe)',
      location: 'Lagos (Remote Possible)',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'mid',
      description: 'Paystack, a Stripe company, is looking for a data analyst to drive data-informed decisions across the business. We have a strong pan-African hiring culture.',
      requirements: 'SQL proficiency required. Python or R a plus. Experience with BI tools (Metabase, Tableau). Business acumen.',
      tags: ['SQL', 'Python', 'Data Analysis', 'Tableau', 'Fintech'],
      salary_min: 45000, salary_max: 70000, salary_currency: 'USD',
      external_url: 'https://paystack.com/careers',
      source: 'tier1', source_name: 'Paystack', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_turing_junior_2024',
      title: 'Junior Frontend Developer',
      company_name: 'Turing',
      location: 'Worldwide Remote',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'junior',
      description: 'Turing matches software engineers globally with top US companies. Great opportunity for fresh African graduates looking to enter the global job market.',
      requirements: '1+ year React or Vue.js. Good English. Ability to work US timezone overlap (4+ hours).',
      tags: ['React', 'JavaScript', 'CSS', 'Git', 'Remote Work'],
      salary_min: 30000, salary_max: 55000, salary_currency: 'USD',
      external_url: 'https://turing.com/apply',
      source: 'tier1', source_name: 'Turing', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_chipper_devops_2024',
      title: 'DevOps Engineer',
      company_name: 'Chipper Cash',
      location: 'US/UK/Africa Remote',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'mid',
      description: 'Chipper Cash enables borderless money transfers across Africa. Our engineering team is distributed across Africa, US, and UK.',
      requirements: 'Kubernetes, Docker, AWS or GCP. CI/CD experience. 3+ years in DevOps/SRE roles.',
      tags: ['Kubernetes', 'Docker', 'AWS', 'GCP', 'CI/CD', 'DevOps'],
      salary_min: 75000, salary_max: 110000, salary_currency: 'USD',
      external_url: 'https://chippercash.com/careers',
      source: 'tier2', source_name: 'Chipper Cash', africa_hiring_signal: 4,
      posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_remote_csm_2024',
      title: 'Customer Success Manager (Remote)',
      company_name: 'Remote.com',
      location: 'Worldwide',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'junior',
      description: 'Remote.com helps companies hire globally. We need CSMs to support our rapidly growing customer base. We hire from everywhere — including Africa.',
      requirements: 'Excellent communication. CRM experience. CEFR B2+ English. Problem-solving mindset.',
      tags: ['Customer Success', 'CRM', 'Communication', 'SaaS'],
      salary_min: 40000, salary_max: 60000, salary_currency: 'USD',
      external_url: 'https://remote.com/careers',
      source: 'tier3', source_name: 'Remote.com', africa_hiring_signal: 4,
      posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_deel_ops_2024',
      title: 'Operations Associate',
      company_name: 'Deel',
      location: 'Global Remote',
      is_remote: true,
      job_type: 'full_time',
      experience_level: 'junior',
      description: 'Deel is the global payroll and compliance platform. We hire globally and actively recruit from emerging markets. Join our operations team.',
      requirements: 'Attention to detail. Google Sheets / Excel proficiency. Strong English. Startup mindset.',
      tags: ['Operations', 'Excel', 'Compliance', 'HR Tech', 'Remote'],
      salary_min: 35000, salary_max: 55000, salary_currency: 'USD',
      external_url: 'https://deel.com/careers',
      source: 'tier1', source_name: 'Deel', africa_hiring_signal: 4,
      posted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_mtn_engineer_2024',
      title: 'Software Engineer',
      company_name: 'MTN Cameroon',
      location: 'Douala, Cameroon',
      is_remote: false,
      job_type: 'full_time',
      experience_level: 'mid',
      description: 'MTN Cameroon is looking for software engineers to join our technology team in Douala. Build mobile and web solutions for millions of Cameroonians.',
      requirements: 'BSc in Computer Science or related field. 2+ years experience. Java, Python, or JavaScript. French required.',
      tags: ['Java', 'Python', 'JavaScript', 'Telecom', 'French'],
      salary_min: 1500000, salary_max: 2500000, salary_currency: 'XAF',
      external_url: 'https://mtn.com/careers',
      source: 'tier2', source_name: 'MTN Cameroon', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      external_id: 'seed_orange_developer_2024',
      title: 'Mobile Developer (iOS/Android)',
      company_name: 'Orange Cameroon',
      location: 'Yaoundé, Cameroon',
      is_remote: false,
      job_type: 'full_time',
      experience_level: 'mid',
      description: 'Orange Cameroon seeks a mobile developer to build and maintain our Orange Money and telecom apps. Join a leading African telecom group.',
      requirements: 'React Native or Flutter. 2+ years mobile development. Published apps a plus. Bilingual (EN/FR) required.',
      tags: ['React Native', 'Flutter', 'iOS', 'Android', 'Mobile', 'French'],
      salary_min: 1200000, salary_max: 2000000, salary_currency: 'XAF',
      external_url: 'https://orange.cm/careers',
      source: 'tier2', source_name: 'Orange Cameroon', africa_hiring_signal: 5,
      posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
  ]
}
